### ISSUE TITLE
Aseprite core tweaks to handle Attachment System tilemaps

### ISSUE THREAD

**Issue by dacap** [aseprite/Attachment-System#127]
The Attachment System requires several tweaks to make some commands work correctly or as expected.

- [ ] Attachment layers are (should be) tilemap layers of 1x1 with one tile
  Sometimes it might be possible that some layer has empty tiles at the edges (legacy file?)
- [ ] Ctrl+mouse (move tool) should show the tile bounds (not the tilemap bounds), same for Ctrl+T to select the bounds of the tile (#95) 
- [x] Shift+H / Shift+V to flip the whole cel should work as with regular layers (#121)
  This might require a customized behavior for the Attachment System because in a regular tilemap we might want to flip the tiles (and then flip the rot/flip flag for tiles / which is not yet supported)
- [x] Start drawing in an empty cel should create a new attachment / assign it and then start drawing in that attachment (#119)

All this is related in some way and requires adjustments in the core or a possibility to handle special events in the program to make it work as if the attachment layers were regular layers.
